"""initial schema

Revision ID: 0001
Revises:
Create Date: 2026-06-03

The baseline schema for hestia's SQLite persistence (#57). Mirrors the SQLAlchemy
models in ``hestia.db`` exactly. Hand-written (not autogenerated at runtime); kept in
sync with the models so a future ``alembic revision --autogenerate`` sees no drift.
"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "0001"
down_revision: str | None = None
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    op.create_table(
        "app_meta",
        sa.Column("key", sa.String(), primary_key=True),
        sa.Column("value", sa.String(), nullable=False),
    )
    op.create_table(
        "nodes",
        sa.Column("key", sa.String(), primary_key=True),
        sa.Column("entry_json", sa.String(), nullable=False),
    )
    op.create_table(
        "automations",
        sa.Column("id", sa.String(), primary_key=True),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("rule_json", sa.String(), nullable=False),
    )
    op.create_table(
        "users",
        sa.Column("username", sa.String(), primary_key=True),
        sa.Column("password_hash", sa.String(), nullable=False),
    )
    op.create_table(
        "user_settings",
        sa.Column("username", sa.String(), sa.ForeignKey("users.username"), primary_key=True),
        sa.Column("locale", sa.String(), nullable=True),
        sa.Column("temp_scale", sa.String(), nullable=True),
        sa.Column("theme", sa.String(), nullable=True),
    )
    op.create_table(
        "audit",
        sa.Column("id", sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column("ts", sa.Float(), nullable=False),
        sa.Column("actor", sa.String(), nullable=True),
        sa.Column("action", sa.String(), nullable=True),
        sa.Column("target", sa.String(), nullable=True),
        sa.Column("detail", sa.String(), nullable=True),
        sa.Column("result", sa.String(), nullable=True),
    )


def downgrade() -> None:
    op.drop_table("audit")
    op.drop_table("user_settings")
    op.drop_table("users")
    op.drop_table("automations")
    op.drop_table("nodes")
    op.drop_table("app_meta")
