/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Recent audit-log rows (newest first, capped 200)
         * @description Requires the viewer role.
         */
        get: operations["audit"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/automations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List every saved automation rule
         * @description Requires the admin role (rules can carry presence-trigger MACs).
         */
        get: operations["listAutomations"];
        put?: never;
        /**
         * Create or replace a rule (the body IS the rule; id is client-supplied)
         * @description Requires the admin role. Authoritative validation is Rule.from_dict.
         */
        post: operations["saveAutomation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/automations/delete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Delete a rule by id (deleted=false, still 200, for an absent id)
         * @description Requires the admin role.
         */
        post: operations["deleteAutomation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/control": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Issue a device control command
         * @description Requires the operator role.
         */
        post: operations["control"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/db/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * SQLite file size + per-table row counts
         * @description Requires the admin role.
         */
        get: operations["dbStats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/discovery": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The full dashboard snapshot (devices + globals + klima + rule grammar)
         * @description Requires the viewer role. The primary read a client polls/refetches.
         */
        get: operations["discovery"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Live updates (Server-Sent Events)
         * @description Requires the viewer role. An unbounded text/event-stream; each `data:` frame is one LiveEvent. `:`-comment keepalives carry no data. Browser/native clients auto-reconnect (the stream closes on a max-lifetime deadline).
         */
        get: operations["events"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ir": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Transmit a saved IR signal via the Flipper
         * @description Requires the operator role.
         */
        post: operations["ir"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Exchange credentials for a session (cookie + optional bearer token)
         * @description Public. Sets the httponly session cookie; with `bearer: true` the 200 body also carries a `token` for `Authorization: Bearer` (native clients).
         */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Clear the session cookie
         * @description Public. Clears the cookie; a bearer client simply discards its token.
         */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Change your own password (verifies the current one)
         * @description Requires a session (viewer+). 401 when not signed in; 403 when the current password is wrong.
         */
        post: operations["changeOwnPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/name": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Set a device's registry labels (name / room / type / endpoint)
         * @description Requires the admin role. Save failure maps to 500 (not 503).
         */
        post: operations["setName"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/rf433": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Discovered 433 MHz devices (newest-seen first)
         * @description Requires the admin role. Engineering observability; empty until the local-433 feeder runs.
         */
        get: operations["rf433"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/rooms/icons": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Shared room→emoji map
         * @description Requires the viewer role. A bare object (room name → emoji); {} when none set.
         */
        get: operations["getRoomIcons"];
        put?: never;
        /**
         * Set one room's emoji (send icon="" to clear)
         * @description Requires the admin role.
         */
        post: operations["setRoomIcon"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scene": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Run a house-wide scene (all lights/blinds on/off)
         * @description Requires the operator role. 200 reports how many device commands landed.
         */
        post: operations["scene"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The logged-in user's UI preferences
         * @description Requires the viewer role. All keys present, null when unset.
         */
        get: operations["getSettings"];
        put?: never;
        /**
         * Update UI preferences (partial — only the keys sent are persisted)
         * @description Requires the viewer role.
         */
        post: operations["setSettings"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List every account (username / role / disabled — never the password hash)
         * @description Requires the admin role. 409 when the SQLite users backend isn't active.
         */
        get: operations["listUsers"];
        put?: never;
        /**
         * Create a new account
         * @description Requires the admin role. 409 on a duplicate username (never an overwrite).
         */
        post: operations["addUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/disabled": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Enable or disable another account
         * @description Requires the admin role. Refuses self (403) and the last enabled admin (409).
         */
        post: operations["setUserDisabled"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/reset-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reset another user's password (admin reset — no current-password check)
         * @description Requires the admin role. Refuses self (403); rotate your own via /api/me/password.
         */
        post: operations["resetUserPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/role": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Change another user's role
         * @description Requires the admin role. Refuses self (403) and the last enabled admin (409).
         */
        post: operations["setUserRole"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/whoami": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The caller's identity + RBAC role
         * @description Requires a session (cookie or bearer). user/role are null when auth is off.
         */
        get: operations["whoami"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/whole-home": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Which devices are opted out of the house-wide "all" sweeps
         * @description Requires the admin role. Registry-only config — kept off DeviceInfo so the device snapshot stays wire-stable for pinned native clients.
         */
        get: operations["getWholeHome"];
        put?: never;
        /**
         * Opt one device in/out of the house-wide "all" sweeps
         * @description Requires the admin role.
         */
        post: operations["setWholeHome"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ActivityEvent
         * @description Heatmap row-flash on every decoded frame with a node; `scene` rides only a function-button frame.
         */
        ActivityEvent: {
            /** Node */
            node: number;
            scene?: components["schemas"]["Scene"];
            /** Ts */
            ts: number;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "activity";
        };
        /**
         * AddUserRequest
         * @description POST /api/users — admin: create an account. ``username`` non-empty, ≤ 64 chars, no ``|`` or ``/``
         *     (the session token is ``username|expiry``); ``password`` 8..1024; ``role`` one of the three. A
         *     duplicate username is a 409 (never an overwrite).
         */
        AddUserRequest: {
            /** Password */
            password: string;
            /**
             * Role
             * @enum {string}
             */
            role: "viewer" | "operator" | "admin";
            /** Username */
            username: string;
        };
        /**
         * AuditEvent
         * @description One audit-log row (store_sql.recent_audit). id/ts are non-null; the five string fields are
         *     nullable at the DB layer (model defensively as str|null), null when the action has no such field.
         */
        AuditEvent: {
            /** Action */
            action: string | null;
            /** Actor */
            actor: string | null;
            /** Detail */
            detail: string | null;
            /** Id */
            id: number;
            /** Result */
            result: string | null;
            /** Target */
            target: string | null;
            /** Ts */
            ts: number;
        };
        /**
         * AuditFeed
         * @description GET /api/audit — newest-first rows (capped 200); `events` always present ([] when audit off).
         */
        AuditFeed: {
            /** Events */
            events: components["schemas"]["AuditEvent"][];
        };
        /**
         * AutomationDeleted
         * @description 200 from POST /api/automations/delete: `deleted` is false (200, not 404) for an absent id.
         */
        AutomationDeleted: {
            /** Deleted */
            deleted: boolean;
            /** Ok */
            ok: boolean;
        };
        /**
         * AutomationSaved
         * @description 200 from POST /api/automations: the saved rule's id (NOT the rule object).
         */
        AutomationSaved: {
            /** Id */
            id: string;
            /** Ok */
            ok: boolean;
        };
        /**
         * AutomationsList
         * @description GET /api/automations — every saved rule. `automations` (NOT `rules`) is always present.
         */
        AutomationsList: {
            /** Automations */
            automations: components["schemas"]["Rule"][];
            /** Ok */
            ok: boolean;
        };
        /**
         * ChangePasswordRequest
         * @description POST /api/me/password — the signed-in user changes their OWN password. ``current`` is verified
         *     (a stolen cookie alone can't rotate it) before the ``new`` hash is written. ``new`` is 8..1024.
         */
        ChangePasswordRequest: {
            /** Current */
            current: string;
            /** New */
            new: string;
        };
        /**
         * ControlCover
         * @description Set a blind/cover position (0..99).
         */
        ControlCover: {
            /**
             * Node
             * @description device node id
             */
            node: number;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            op: "cover";
            /**
             * Value
             * @description cover position 0..99
             */
            value: number;
        };
        /**
         * ControlError
         * @description The 400 (malformed) / 503 (device unavailable) body: ``ok`` false + a human error string.
         */
        ControlError: {
            /** Error */
            error: string;
            /** Ok */
            ok: boolean;
        };
        /**
         * ControlLevel
         * @description Set a dimmer level (0..99).
         */
        ControlLevel: {
            /**
             * Node
             * @description device node id
             */
            node: number;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            op: "level";
            /**
             * Value
             * @description dim level 0..99
             */
            value: number;
        };
        /** @description A device control command — one variant per device op. */
        ControlRequest: components["schemas"]["ControlSwitch"] | components["schemas"]["ControlThermostatPower"] | components["schemas"]["ControlLevel"] | components["schemas"]["ControlCover"] | components["schemas"]["ControlThermostat"];
        /**
         * ControlSuccess
         * @description The 200 body when a control command reaches the device: ``ok`` true + the ``sent`` wire frame.
         */
        ControlSuccess: {
            /** Ok */
            ok: boolean;
            /**
             * Sent
             * @description the device command frame that was sent, hex-encoded
             */
            sent: string;
        };
        /**
         * ControlSwitch
         * @description Turn a relay/light on or off (optionally a single gang of a multi-gang node).
         */
        ControlSwitch: {
            /**
             * Endpoint
             * @description multi-gang channel 1 or 2; omit for single-gang
             */
            endpoint?: number;
            /**
             * Node
             * @description device node id
             */
            node: number;
            /** On */
            on: boolean;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            op: "switch";
        };
        /**
         * ControlThermostat
         * @description Set a thermostat/TRV target temperature (4..28 °C).
         */
        ControlThermostat: {
            /**
             * Celsius
             * @description target °C, 4..28
             */
            celsius: number;
            /**
             * Node
             * @description device node id
             */
            node: number;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            op: "thermostat";
        };
        /**
         * ControlThermostatPower
         * @description Power a thermostat/TRV on or off.
         */
        ControlThermostatPower: {
            /**
             * Node
             * @description device node id
             */
            node: number;
            /** On */
            on: boolean;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            op: "thermostat_power";
        };
        /**
         * DbStats
         * @description GET /api/db/stats — SQLite on-disk size + per-table row counts (admin). ``tables`` maps each
         *     tracked table name to its current row count.
         */
        DbStats: {
            /** File Bytes */
            file_bytes: number;
            /** Tables */
            tables: {
                [key: string]: number;
            };
        };
        /**
         * DeviceInfo
         * @description One device, merged from the classifier + the user registry (``proxy._discovery_entry``). The base
         *     + live-state fields are ALWAYS present (required), null when unseen — so `0`/`false` are never lost.
         *     The registry labels (``name``/``room``/``endpoint_names``) are OPTIONAL — absent until set, never null.
         *     ``confidence`` is usually a string but a legacy/hand-edited registry node (a ``type`` without a
         *     ``confidence``) can surface null, so the contract admits it. NOTE: the whole-home scene opt-out
         *     (``exclude_from_all``) is deliberately NOT exposed here — it lives only on the dedicated
         *     ``/api/whole-home`` surface, so adding it never changes this (client-decoded) response shape.
         */
        DeviceInfo: {
            /** Battery */
            battery: number | null;
            /** Confidence */
            confidence: string | null;
            /** Door */
            door: string | null;
            /** Endpoint Names */
            endpoint_names?: {
                [key: string]: string;
            };
            /** Endpoints */
            endpoints: {
                [key: string]: boolean;
            } | null;
            /** Energy Kwh */
            energy_kwh: number | null;
            /** Last Seen */
            last_seen: string | null;
            /** Level */
            level: number | null;
            /** Motion */
            motion: boolean | null;
            /** Name */
            name?: string;
            /** Power */
            power: string | null;
            /** Power W */
            power_w: number | null;
            /** Room */
            room?: string;
            /** Setpoint */
            setpoint: number | null;
            /** Switch */
            switch: boolean | null;
            /** Temperature */
            temperature: number | null;
            /** Thermostat Last Cmd */
            thermostat_last_cmd: number | null;
            /** Thermostat On */
            thermostat_on: boolean | null;
            /** Type */
            type: string;
            /** Voltage V */
            voltage_v: number | null;
        };
        /**
         * DeviceStatePatch
         * @description A partial of DeviceInfo — exactly the live-state keys a frame can change (State.apply's `changed`
         *     map, after `scene` is popped). Discovery-side fields (power/type/confidence/battery/last_seen) never
         *     ride a `state` event — they arrive via a discovery_changed refetch.
         */
        DeviceStatePatch: {
            /** Door */
            door?: string | null;
            /** Endpoints */
            endpoints?: {
                [key: string]: boolean;
            } | null;
            /** Energy Kwh */
            energy_kwh?: number | null;
            /** Level */
            level?: number | null;
            /** Motion */
            motion?: boolean | null;
            /** Power W */
            power_w?: number | null;
            /** Setpoint */
            setpoint?: number | null;
            /** Switch */
            switch?: boolean | null;
            /** Temperature */
            temperature?: number | null;
            /** Thermostat On */
            thermostat_on?: boolean | null;
            /** Voltage V */
            voltage_v?: number | null;
        };
        /**
         * Discovery
         * @description ``GET /api/discovery`` — the whole dashboard snapshot. Every key is always present; ``klima_state``
         *     is null until an A/C IR command is seen, ``env_override`` is null unless ``HESTIA_MODE`` pins the mode.
         */
        Discovery: {
            /** Devices */
            devices: {
                [key: string]: components["schemas"]["DeviceInfo"];
            };
            /** Env Override */
            env_override: string | null;
            globals: components["schemas"]["Globals"];
            /** Ir Buttons */
            ir_buttons: components["schemas"]["IrButton"][];
            klima: components["schemas"]["Klima"];
            klima_state: components["schemas"]["KlimaState"] | null;
            /** Mode */
            mode: string;
            rule_vocab: components["schemas"]["RuleVocab"];
            summary: components["schemas"]["Summary"];
            /** Target Mode */
            target_mode: string;
        };
        /**
         * DiscoveryChangedEvent
         * @description Re-fetch GET /api/discovery (identity/name/classifier change). No payload.
         */
        DiscoveryChangedEvent: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "discovery_changed";
        };
        /**
         * Globals
         * @description Node-less global fields (``proxy.globals_snapshot``). Every key is ALWAYS present (required),
         *     null when its poller is off. ``outdoor_temp_ts`` is the ISO ts of the last outdoor sample (freshness
         *     badge); ``outdoor_battery_ok`` is the local 433 sensor's battery flag (false = low).
         */
        Globals: {
            /** Crib Temp */
            crib_temp: number | null;
            /** Outdoor Battery Ok */
            outdoor_battery_ok: boolean | null;
            /** Outdoor Humidity */
            outdoor_humidity: number | null;
            /** Outdoor Temp */
            outdoor_temp: number | null;
            /** Outdoor Temp Ts */
            outdoor_temp_ts: string | null;
        };
        /** GlobalsEvent */
        GlobalsEvent: {
            fields: components["schemas"]["GlobalsPatch"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "globals";
        };
        /**
         * GlobalsPatch
         * @description A partial of Globals — the changed global field(s) in a `globals` event (1 key for the niania /
         *     Open-Meteo poll + its ts, up to 4 for a 433 reading: temp, humidity, ts, battery).
         */
        GlobalsPatch: {
            /** Crib Temp */
            crib_temp?: number | null;
            /** Outdoor Battery Ok */
            outdoor_battery_ok?: boolean | null;
            /** Outdoor Humidity */
            outdoor_humidity?: number | null;
            /** Outdoor Temp */
            outdoor_temp?: number | null;
            /** Outdoor Temp Ts */
            outdoor_temp_ts?: string | null;
        };
        /**
         * IrButton
         * @description A configured one-tap IR button (``HESTIA_IR_BUTTONS``) → transmits a saved Flipper signal.
         */
        IrButton: {
            /** Button */
            button: string;
            /** File */
            file: string;
            /** Label */
            label: string;
        };
        /**
         * IrRequest
         * @description POST /api/ir — transmit a saved Flipper IR signal (same 200/400/503 envelopes as /api/control).
         */
        IrRequest: {
            /** Button */
            button: string;
            /** File */
            file: string;
        };
        /**
         * Klima
         * @description The A/C control map parsed from the klima.ir signal names — an empty ``{}`` when no klima.ir is
         *     present, so every field is OPTIONAL (absent, never null). ``modes``/``power_on`` map each mode to its
         *     sorted temps; ``presets`` carries ``off`` + any non-temp signal.
         */
        Klima: {
            /** File */
            file?: string;
            /** Modes */
            modes?: {
                [key: string]: number[];
            };
            /** Power On */
            power_on?: {
                [key: string]: number[];
            };
            /** Presets */
            presets?: string[];
        };
        /** KlimaEvent */
        KlimaEvent: {
            klima: components["schemas"]["KlimaState"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "klima";
        };
        /**
         * KlimaState
         * @description The A/C state derived from IR traffic (``state``): power + optional mode/target.
         */
        KlimaState: {
            /** Mode */
            mode: string | null;
            /** Power */
            power: boolean;
            /** Temp */
            temp: number | null;
        };
        /** @description One Server-Sent-Events frame (the JSON after `data:`). */
        LiveEvent: components["schemas"]["DiscoveryChangedEvent"] | components["schemas"]["StateEvent"] | components["schemas"]["ActivityEvent"] | components["schemas"]["GlobalsEvent"] | components["schemas"]["KlimaEvent"];
        /**
         * LoginRequest
         * @description POST /api/login body. ``bearer: true`` opts a native client into a token in the response (which
         *     it then sends as ``Authorization: Bearer``); the browser omits it and relies on the httponly cookie.
         */
        LoginRequest: {
            /** Bearer */
            bearer?: boolean;
            /** Password */
            password: string;
            /** User */
            user: string;
        };
        /**
         * LoginSuccess
         * @description 200 from /api/login. ``token`` is present ONLY when the request set ``bearer: true``.
         */
        LoginSuccess: {
            /** Ok */
            ok: boolean;
            /** Token */
            token?: string;
            /** User */
            user: string;
        };
        /**
         * NameRequest
         * @description POST /api/name — set a device's registry labels. ``node`` is required; at least one of
         *     name/room/type must be present (server-enforced cross-field, not expressible here). name/room
         *     accept null (clear); type is a DeviceType; ep is a multi-gang channel label. Unknown keys → 400.
         */
        NameRequest: {
            /** Ep */
            ep?: number | null;
            /** Name */
            name?: string | null;
            /** Node */
            node: number;
            /**
             * Op
             * @constant
             */
            op?: "name";
            /** Room */
            room?: string | null;
            /** Type */
            type?: ("light" | "blind" | "thermostat" | "door" | "motion" | "smoke" | "water" | "plug" | "unknown") | null;
        };
        /**
         * OkResult
         * @description A bare ``{ok: true}`` acknowledgement (e.g. /api/logout).
         */
        OkResult: {
            /** Ok */
            ok: boolean;
        };
        /**
         * ResetPasswordRequest
         * @description POST /api/users/reset-password — admin: set ANOTHER user's password (no current-password check).
         *     Refuses self (an admin rotates their OWN credential via /api/me/password, which verifies the current
         *     one). NOTE the field is ``new`` (not ``password``).
         */
        ResetPasswordRequest: {
            /** New */
            new: string;
            /** Username */
            username: string;
        };
        /**
         * Rf433Device
         * @description One discovered 433 MHz device (``rf433.Rf433Registry.snapshot``). ``fields`` is the last decoded
         *     packet's JSON-safe scalars (rtl_433 ``time``/``mic`` noise stripped). All five keys are always present.
         */
        Rf433Device: {
            /** Count */
            count: number;
            /** Fields */
            fields: {
                [key: string]: boolean | number | string;
            };
            /** First Seen */
            first_seen: number;
            /** Key */
            key: string;
            /** Last Seen */
            last_seen: number;
        };
        /**
         * Rf433Feed
         * @description GET /api/rf433 — every decoded 433 device, newest-seen first (admin observability). ``devices`` is
         *     ``[]`` until the local-433 feeder is running.
         */
        Rf433Feed: {
            /** Devices */
            devices: components["schemas"]["Rf433Device"][];
        };
        /**
         * RoomIconRequest
         * @description POST /api/rooms/icons — set one shared room emoji. Send icon="" (empty string, NOT null) to clear.
         */
        RoomIconRequest: {
            /** Icon */
            icon: string;
            /** Room */
            room: string;
        };
        /**
         * Rule
         * @description A saved automation rule (automations.Rule.to_dict) — all 7 keys ALWAYS present in the output.
         */
        Rule: {
            /** Actions */
            actions: components["schemas"]["RuleAction"][];
            /** Conditions */
            conditions: (components["schemas"]["TimeWindowCondition"] | components["schemas"]["StatePredicate"])[];
            /** Debounce */
            debounce: number;
            /** Enabled */
            enabled: boolean;
            /** Id */
            id: string;
            /** Modes */
            modes: string[];
            /** Trigger */
            trigger: components["schemas"]["TriggerScene"] | components["schemas"]["TriggerState"] | components["schemas"]["TriggerTime"] | components["schemas"]["TriggerSun"] | components["schemas"]["TriggerPresence"] | components["schemas"]["TriggerCron"];
        };
        /**
         * RuleAction
         * @description One action. Only `op` (+ ir's file/button) is validated at save; all other per-op fields are
         *     author-supplied and pass through verbatim — so this is open (extra=allow), not a closed per-op union.
         */
        RuleAction: {
            /**
             * Op
             * @enum {string}
             */
            op: "raw" | "cover" | "level" | "switch" | "lights" | "thermostat" | "thermostat_power" | "ir";
        } & {
            [key: string]: unknown;
        };
        /**
         * RuleInput
         * @description POST /api/automations body. id/trigger/actions required; enabled/modes/debounce/conditions are
         *     optional (server-defaulted by Rule.from_dict: enabled=true, modes=[proxy,standalone], debounce=0,
         *     conditions=[]). Authoritative validation is Rule.from_dict — this shape is the codegen guide.
         */
        RuleInput: {
            /** Actions */
            actions: components["schemas"]["RuleAction"][];
            /** Conditions */
            conditions?: (components["schemas"]["TimeWindowCondition"] | components["schemas"]["StatePredicate"])[];
            /** Debounce */
            debounce?: number;
            /** Enabled */
            enabled?: boolean;
            /** Id */
            id: string;
            /** Modes */
            modes?: string[];
            /** Trigger */
            trigger: components["schemas"]["TriggerScene"] | components["schemas"]["TriggerState"] | components["schemas"]["TriggerTime"] | components["schemas"]["TriggerSun"] | components["schemas"]["TriggerPresence"] | components["schemas"]["TriggerCron"];
        };
        /**
         * RuleVocab
         * @description The automation-rule grammar the guided form builds from (``automations.rule_vocab``).
         */
        RuleVocab: {
            /** Cmp Ops */
            cmp_ops: string[];
            /** Condition Types */
            condition_types: string[];
            /** Frame Action Ops */
            frame_action_ops: string[];
            /** Modes */
            modes: string[];
            /** Presence Events */
            presence_events: string[];
            /** State Fields */
            state_fields: {
                [key: string]: boolean;
            };
            /** Sun Events */
            sun_events: string[];
            /** Trigger Types */
            trigger_types: string[];
        };
        /**
         * Scene
         * @description A function-button press riding an `activity` event. `kind` distinguishes the two frame types.
         */
        Scene: {
            /** Id */
            id: number;
            /**
             * Kind
             * @enum {string}
             */
            kind: "scene" | "central";
        };
        /**
         * SceneRequest
         * @description POST /api/scene — fan one house-wide scene out across the per-device control path.
         */
        SceneRequest: {
            /**
             * Op
             * @enum {string}
             */
            op: "lights_off" | "lights_on" | "blinds_down" | "blinds_up";
        };
        /**
         * SceneResult
         * @description 200 from /api/scene: how many of the scene's per-device commands the gateway accepted.
         */
        SceneResult: {
            /** Ok */
            ok: boolean;
            /** Sent */
            sent: number;
            /** Total */
            total: number;
        };
        /**
         * SetDisabledRequest
         * @description POST /api/users/disabled — admin: enable/disable ANOTHER account. Refuses self + the last enabled admin.
         */
        SetDisabledRequest: {
            /** Disabled */
            disabled: boolean;
            /** Username */
            username: string;
        };
        /**
         * SetRoleRequest
         * @description POST /api/users/role — admin: change ANOTHER user's role. Refuses self (no self-demote) and the
         *     last enabled admin (server-enforced). ``username`` only has to be non-empty (it names an existing
         *     account, so the create-time char rules don't re-apply).
         */
        SetRoleRequest: {
            /**
             * Role
             * @enum {string}
             */
            role: "viewer" | "operator" | "admin";
            /** Username */
            username: string;
        };
        /**
         * Settings
         * @description GET /api/settings — the logged-in user's UI prefs. All three keys are ALWAYS present, null when
         *     unset (an unauthenticated / no-row request returns all-null, never an error).
         */
        Settings: {
            /** Locale */
            locale: string | null;
            /** Temp Scale */
            temp_scale: string | null;
            /** Theme */
            theme: string | null;
        };
        /**
         * SettingsUpdate
         * @description POST /api/settings — a PARTIAL update: only the keys present are persisted (absent keys are left
         *     untouched). null clears a field. temp_scale ∈ {C,F,K}. locale ≤ 35 chars.
         */
        SettingsUpdate: {
            /** Locale */
            locale?: string | null;
            /** Temp Scale */
            temp_scale?: ("C" | "F" | "K") | null;
            /** Theme */
            theme?: string | null;
        };
        /** StateEvent */
        StateEvent: {
            fields: components["schemas"]["DeviceStatePatch"];
            /** Node */
            node: number;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "state";
        };
        /**
         * StatePredicate
         * @description A condition with NO `type` key (the absence IS the discriminant vs time_window).
         */
        StatePredicate: {
            /** Endpoint */
            endpoint?: number;
            /**
             * Field
             * @enum {string}
             */
            field: "door" | "motion" | "level" | "switch" | "setpoint" | "thermostat_on" | "temperature" | "power_w" | "energy_kwh" | "voltage_v" | "crib_temp" | "outdoor_temp";
            /** Node */
            node?: number;
            /**
             * Op
             * @enum {string}
             */
            op: "eq" | "ne" | "lt" | "le" | "gt" | "ge";
            /** Value */
            value: boolean | number | string;
        };
        /**
         * Summary
         * @description Discovery roster counters (``web._summary``).
         */
        Summary: {
            /** Confirmed */
            confirmed: number;
            /** Total */
            total: number;
            /** Unknown */
            unknown: number;
        };
        /**
         * TimeWindowCondition
         * @description A time-of-day guard condition. `days` is OMITTED entirely when unset (unlike time/sun triggers).
         */
        TimeWindowCondition: {
            /** Days */
            days?: number[];
            /** End */
            end: string;
            /** Start */
            start: string;
            /**
             * Type
             * @constant
             */
            type: "time_window";
        };
        /** TriggerCron */
        TriggerCron: {
            /** Expr */
            expr: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "cron";
        };
        /** TriggerPresence */
        TriggerPresence: {
            /**
             * Event
             * @enum {string}
             */
            event: "arrive" | "leave";
            /** Mac */
            mac: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "presence";
        };
        /** TriggerScene */
        TriggerScene: {
            /** Node */
            node: number;
            /** Scene Id */
            scene_id: number;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "scene";
        };
        /** TriggerState */
        TriggerState: {
            /** Endpoint */
            endpoint?: number;
            /**
             * Field
             * @enum {string}
             */
            field: "door" | "motion" | "level" | "switch" | "setpoint" | "thermostat_on" | "temperature" | "power_w" | "energy_kwh" | "voltage_v" | "crib_temp" | "outdoor_temp";
            /** Node */
            node?: number;
            /**
             * Op
             * @enum {string}
             */
            op: "eq" | "ne" | "lt" | "le" | "gt" | "ge";
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "state";
            /** Value */
            value: boolean | number | string;
        };
        /** TriggerSun */
        TriggerSun: {
            /** Days */
            days: number[] | null;
            /**
             * Event
             * @enum {string}
             */
            event: "sunrise" | "sunset";
            /** Offset Min */
            offset_min: number;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "sun";
        };
        /** TriggerTime */
        TriggerTime: {
            /** At */
            at: string;
            /** Days */
            days: number[] | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "time";
        };
        /**
         * UserRow
         * @description One account in the admin user list (``store_sql.list_users``) — username / role / disabled,
         *     NEVER the password hash.
         */
        UserRow: {
            /** Disabled */
            disabled: boolean;
            /**
             * Role
             * @enum {string}
             */
            role: "viewer" | "operator" | "admin";
            /** Username */
            username: string;
        };
        /**
         * UsersList
         * @description GET /api/users — every account (admin). ``users`` is always present; there is NO top-level ``ok``.
         */
        UsersList: {
            /** Users */
            users: components["schemas"]["UserRow"][];
        };
        /**
         * WhoAmI
         * @description GET /api/whoami — the caller's identity + RBAC role; both null when auth is off (loopback/dev).
         */
        WhoAmI: {
            /** Role */
            role: string | null;
            /** User */
            user: string | null;
        };
        /**
         * WholeHomeConfig
         * @description GET /api/whole-home — what is opted out of the house-wide "all lights / all blinds" sweeps.
         *     Registry-only config (deliberately NOT in DeviceInfo, so adding the opt-out never changes the
         *     device-snapshot wire shape a pinned native client decodes). ``excluded_nodes`` = whole devices;
         *     ``excluded_endpoints`` = single gangs of a multi-gang switch (node id → sorted gang numbers).
         */
        WholeHomeConfig: {
            /** Excluded Endpoints */
            excluded_endpoints: {
                [key: string]: number[];
            };
            /** Excluded Nodes */
            excluded_nodes: number[];
        };
        /**
         * WholeHomeRequest
         * @description POST /api/whole-home — opt one device in (``exclude``=false) / out (true) of the house-wide
         *     "all" sweeps. With ``ep`` (gang 1 or 2, like the control op's ``endpoint``) the opt-out targets
         *     that single gang of a multi-gang switch instead of the whole node.
         */
        WholeHomeRequest: {
            /** Ep */
            ep?: number | null;
            /** Exclude */
            exclude: boolean;
            /**
             * Node
             * @description device node id
             */
            node: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    audit: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description the audit feed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditFeed"];
                };
            };
        };
    };
    listAutomations: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description the rules */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AutomationsList"];
                };
            };
        };
    };
    saveAutomation: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RuleInput"];
            };
        };
        responses: {
            /** @description saved */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AutomationSaved"];
                };
            };
            /** @description invalid rule */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ControlError"];
                };
            };
            /** @description save failed */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ControlError"];
                };
            };
        };
    };
    deleteAutomation: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    id: string;
                };
            };
        };
        responses: {
            /** @description deleted (or no-op) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AutomationDeleted"];
                };
            };
            /** @description invalid id */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ControlError"];
                };
            };
            /** @description save failed */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ControlError"];
                };
            };
        };
    };
    control: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ControlRequest"];
            };
        };
        responses: {
            /** @description command sent to the device */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ControlSuccess"];
                };
            };
            /** @description malformed command */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ControlError"];
                };
            };
            /** @description device unavailable / command rejected */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ControlError"];
                };
            };
        };
    };
    dbStats: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description the database stats */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DbStats"];
                };
            };
        };
    };
    discovery: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description the current snapshot */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Discovery"];
                };
            };
        };
    };
    events: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description the event stream (one LiveEvent per data frame) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": components["schemas"]["LiveEvent"];
                };
            };
        };
    };
    ir: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IrRequest"];
            };
        };
        responses: {
            /** @description transmitted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResult"];
                };
            };
            /** @description malformed */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ControlError"];
                };
            };
            /** @description IR disabled / queue full / failed */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ControlError"];
                };
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description authenticated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginSuccess"];
                };
            };
            /** @description invalid credentials */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ControlError"];
                };
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description logged out */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResult"];
                };
            };
        };
    };
    changeOwnPassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangePasswordRequest"];
            };
        };
        responses: {
            /** @description password changed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResult"];
                };
            };
            /** @description invalid / missing fields */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ControlError"];
                };
            };
            /** @description not signed in */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ControlError"];
                };
            };
            /** @description current password is incorrect */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ControlError"];
                };
            };
            /** @description account no longer exists (or SQLite backend inactive) */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ControlError"];
                };
            };
        };
    };
    setName: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NameRequest"];
            };
        };
        responses: {
            /** @description labels saved */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResult"];
                };
            };
            /** @description malformed */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ControlError"];
                };
            };
            /** @description registry save failed */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ControlError"];
                };
            };
        };
    };
    rf433: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description the 433 device feed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Rf433Feed"];
                };
            };
        };
    };
    getRoomIcons: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description the room→icon map */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    setRoomIcon: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RoomIconRequest"];
            };
        };
        responses: {
            /** @description saved */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResult"];
                };
            };
            /** @description malformed */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ControlError"];
                };
            };
        };
    };
    scene: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SceneRequest"];
            };
        };
        responses: {
            /** @description scene dispatched */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SceneResult"];
                };
            };
            /** @description unknown scene */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ControlError"];
                };
            };
        };
    };
    getSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description the user's settings */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Settings"];
                };
            };
        };
    };
    setSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SettingsUpdate"];
            };
        };
        responses: {
            /** @description saved */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResult"];
                };
            };
            /** @description malformed */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ControlError"];
                };
            };
        };
    };
    listUsers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description the accounts */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UsersList"];
                };
            };
            /** @description user management requires the SQLite backend */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ControlError"];
                };
            };
        };
    };
    addUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddUserRequest"];
            };
        };
        responses: {
            /** @description account created */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResult"];
                };
            };
            /** @description invalid username / password / role */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ControlError"];
                };
            };
            /** @description duplicate username (or SQLite backend inactive) */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ControlError"];
                };
            };
        };
    };
    setUserDisabled: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetDisabledRequest"];
            };
        };
        responses: {
            /** @description updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResult"];
                };
            };
            /** @description invalid username / disabled flag */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ControlError"];
                };
            };
            /** @description cannot disable your own account */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ControlError"];
                };
            };
            /** @description no such user */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ControlError"];
                };
            };
            /** @description would leave no enabled admin (or SQLite backend inactive) */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ControlError"];
                };
            };
        };
    };
    resetUserPassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResetPasswordRequest"];
            };
        };
        responses: {
            /** @description password reset */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResult"];
                };
            };
            /** @description invalid username / password */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ControlError"];
                };
            };
            /** @description use change-password for your own account */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ControlError"];
                };
            };
            /** @description no such user */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ControlError"];
                };
            };
            /** @description SQLite backend inactive */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ControlError"];
                };
            };
        };
    };
    setUserRole: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetRoleRequest"];
            };
        };
        responses: {
            /** @description role changed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResult"];
                };
            };
            /** @description invalid username / role */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ControlError"];
                };
            };
            /** @description cannot change your own role */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ControlError"];
                };
            };
            /** @description no such user */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ControlError"];
                };
            };
            /** @description would leave no enabled admin (or SQLite backend inactive) */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ControlError"];
                };
            };
        };
    };
    whoami: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description the current session's identity */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WhoAmI"];
                };
            };
        };
    };
    getWholeHome: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description the opt-out config */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WholeHomeConfig"];
                };
            };
        };
    };
    setWholeHome: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WholeHomeRequest"];
            };
        };
        responses: {
            /** @description saved */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResult"];
                };
            };
            /** @description malformed */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ControlError"];
                };
            };
            /** @description registry save failed */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ControlError"];
                };
            };
        };
    };
}
